name       : alkimia
version    : 7.0.2
release    : 3
source     :
    - https://download.kde.org/stable/alkimia/7.0.2/alkimia-7.0.2.tar.xz : 59e6b10d819479bc8dde53a8b10e6ec05e9d465c5e035528a5c0b036456a2454
license    : LGPL-2.1
component  : programming.library
summary    : Common storage and business logic used by financial applications
description: |
    Alkimia is the infrastructure for common storage and business logic that will be used by all financial applications in KDE. The target is to share financial related information over application bounderies.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
