name       : alkimia
version    : 8.0.2
release    : 5
source     :
    - https://download.kde.org/stable/alkimia/8.0.2/alkimia-8.0.2.tar.xz : 616f7736fde8ce8acec4575f14e856fabfefb0961d932198d42fbd9a639a852a
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Common storage and business logic used by financial applications
description: |
    Alkimia is the infrastructure for common storage and business logic that will be used by all financial applications in KDE. The target is to share financial related information over application bounderies.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kdelibs4support-devel
    - knewstuff-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
