name       : alkimia
version    : 8.0.4
release    : 7
source     :
    - https://cdn.download.kde.org/stable/alkimia/8.0.4/alkimia-8.0.4.tar.xz : 0004a7068dff0aa2cb6f47f70d21c129073be11f2edb21f14512bc4470487d1f
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Common storage and business logic used by financial applications
description: |
    Alkimia is the infrastructure for common storage and business logic that will be used by all financial applications in KDE. The target is to share financial related information over application bounderies.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - kdelibs4support-devel
    - knewstuff-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
