name       : alkimia
version    : 8.0.1
release    : 4
source     :
    - https://download.kde.org/stable/alkimia/8.0.1/alkimia-8.0.1.tar.xz : f5601780f6ed95b5e14dd3a243ecd1afbdbdb522f0e32dec2fb86933ec363115
license    : LGPL-2.1
component  : programming.library
summary    : Common storage and business logic used by financial applications
description: |
    Alkimia is the infrastructure for common storage and business logic that will be used by all financial applications in KDE. The target is to share financial related information over application bounderies.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5WebKit) 
    - extra-cmake-modules
    - kdelibs4support-devel
    - knewstuff-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install