name       : alkimia
version    : 7.0
release    : 1
source     :
    - https://cdn.download.kde.org/stable/alkimia/7.0/src/alkimia-7.0.tar.xz : 0c70d0d3b6c020d5bcf92b6f1c395f3bad53a08d4e2b2c17e70c2079e9f43158
license    : LGPL-2.1
component  : programming.library
summary    : Common storage and business logic used by financial applications
description: |
    Alkimia is the infrastructure for common storage and business logic that will be used by all financial applications in KDE. The target is to share financial related information over application bounderies.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
