name       : alkimia
version    : 8.1.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/alkimia/8.1.0/alkimia-8.1.0.tar.xz : 916807352707b0490cdd9ca65682eff73b00ca523029bda6fe7a2749a1bc927c
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Common storage and business logic used by financial applications
description: |
    Alkimia is the infrastructure for common storage and business logic that will be used by all financial applications in KDE. The target is to share financial related information over application bounderies.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5WebKit)
    - kiconthemes-devel
    - kio-devel
    - knewstuff-devel
    - ktextwidgets-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
