name       : alkimia
version    : 7.0.1
release    : 2
source     :
    - https://cdn.download.kde.org/stable/alkimia/7.0.1/src/alkimia-7.0.1.tar.xz : 42c49025b3f8489dcbc5df55101ef95bc920e160b9d5ecf573a88062883931bb
license    : LGPL-2.1
component  : programming.library
summary    : Common storage and business logic used by financial applications
description: |
    Alkimia is the infrastructure for common storage and business logic that will be used by all financial applications in KDE. The target is to share financial related information over application bounderies.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
